// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIrFGKNfeFbJZP-Xx3DDh8uTC3rIxomR0',
    appId: '1:445079146163:android:f40788f7198f29977beac6',
    messagingSenderId: '445079146163',
    projectId: 'wealtai-inexor',
    storageBucket: 'wealtai-inexor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQF5ys0ySmP2WYAxyX6AxnqRGVfqoEI5o',
    appId: '1:445079146163:ios:33eea0789489d6817beac6',
    messagingSenderId: '445079146163',
    projectId: 'wealtai-inexor',
    storageBucket: 'wealtai-inexor.firebasestorage.app',
    androidClientId:
        '445079146163-0nhflb0p1665houlm3tvij3jh81jc743.apps.googleusercontent.com',
    iosClientId:
        '445079146163-k7qpk0fnvp21k4sk0h462tqgcd48okvr.apps.googleusercontent.com',
    iosBundleId: 'com.inexor.wealthnx.ai',
  );
}
