name: wealthnx
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.6.0


dependencies:
  permission_handler: ^11.3.1
#  speech_to_text: ^7.0.0
#  record: ^5.2.0
  http: ^1.2.2
  python_ffi: ^0.4.4
  fl_chart: ^0.70.2
  animations: ^2.0.11
  intl: ^0.20.0
  provider: ^6.1.2
  country_code_picker: ^3.1.0
  flutter_svg: ^2.0.17
  #  dio: ^5.0.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  universal_html: ^2.0.8
  shared_preferences: ^2.0.6
  universal_io: ^2.0.4
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  flutter_link_previewer: ^3.2.2
  syncfusion_flutter_charts: ^28.1.33
  k_chart_plus_deeping: ^1.0.2-5.2.2.3

  # /----------------------New Sturcture
  get: ^4.7.2
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.12
#  flutter_launcher_icons: "^0.14.3"
  get_secure_storage: ^1.0.5
  awesome_dialog: ^3.2.1
  google_fonts:
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  timeago: ^3.7.1
  google_sign_in: ^6.2.2
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  local_auth: ^2.3.0
  carousel_slider: ^5.1.1
  pie_chart_sz: ^1.1.1
  flutter_markdown:
  wakelock_plus: ^1.1.3
  
  upgrader: ^12.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # webview_flutter: ^4.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/applogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/


    # ------------old
    - assets/config.json
    - assets/icons/usa.png
    - assets/env.json
    - assets/icons/

